// Shared ignore patterns for filesystem walks.
// Keep JSON files (package.json, tsconfig.json, etc.) but skip lockfiles and obvious binaries.
export const DEFAULT_IGNORE_PATTERNS = [
  "*.lock",
  "*.bin",
  "*.ipynb",
  "*.pyc",
  "*.onnx",
  // Non-code text files (osgrep is for CODE search)
  "*.txt",
  "*.log",
  "*.csv",
  // Safety nets for nested non-git folders
  "**/node_modules/**",
  "**/dist/**",
  "**/build/**",
  "**/out/**",
  "**/target/**",
  "**/__pycache__/**",
  "**/coverage/**",
  "**/venv/**",
  // Test fixtures and benchmark data
  "**/fixtures/**",
  "**/benchmark/**",
  "**/testdata/**",
  "**/__fixtures__/**",
  "**/__snapshots__/**",
  // Lockfiles across ecosystems
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
  "composer.lock",
  "Cargo.lock",
  "Gemfile.lock",
  // Security: Sensitive files that should never be indexed
  ".env",
  ".env.*",
  "*.key",
  "*.pem",
  "*.p12",
  "*.pfx",
  "*.p8",
  "**/.ssh/**",
  "id_rsa",
  "id_ed25519",
  "*.pub",
  "**/.gnupg/**",
  "*.gpg",
  "**/.aws/**",
  "**/.gcloud/**",
  "**/.azure/**",
  "secrets.*",
  "credentials.*",
  // IDE and OS files
  ".DS_Store",
  "**/.idea/**",
  "**/.vscode/**",
  "Thumbs.db",
];
